- .gitignore
- apps/server/.eslintrc.js
- apps/server/.prettierrc
- apps/server/package.json
- apps/server/pnpm-lock.yaml
- apps/server/src/app.controller.spec.ts
- apps/server/src/app.controller.ts
- apps/server/src/app.module.ts
- apps/server/src/main.ts
- apps/server/test/app.e2e-spec.ts
- package-lock.json
- package.json
- pnpm-lock.yaml
- Nest.js 기본 linter와 추가적인 항목을 설정했습니다.
- #6
> chore: configure linter

- apps/client/.eslintrc.json
- 프론트엔드 ESLint 설정 파일을 수정했습니다.
- `js` 파일이 Lint 실행시 오류를 발생시키는 문제가 있어, 해당 부분을 린트 실행시 제외하도록 수정했습니다.
- #14
> chore: update ESLint ignore patterns to include PostCSS and Tailwind config files

- .github/workflows/deploy.yml
- pnpm-lock.yaml
- 배포 자동화를 위한 CI/CD 설정을 진행했습니다.
- 정적파일은 빌드해서 오브젝트 스토리지로, 백엔드는 바로 pull을 이용해서 업데이트하고 재시작시킵니다.
- close #17
> chore: setup CI/CD

- apps/client/src/features/session/qa/qa.type.ts
> fix(fe): update import path for Session type in QA module

- .github/workflows/deploy.yml
- pnpm-lock.yaml
- 오브젝트 스토리지로 보내기전에 경로 이동 추가
- close #17
> fix: modify CI/CD script

- .github/workflows/deploy.yml
- 리전 설정과 경로 문제, nvm 설정을 통해서 배포과정에서 나온 에러들을 해결했습니다.
- #17
> fix: fix CD script

- .github/workflows/deploy.yml
- 프리즈마 이슈로 서버가 제대로 동작하지않아서 스크립트를 추가해서 해결했습니다.
> fix: add pnpx prisma generate

- apps/server/src/main.ts
- apps/server/src/users/swagger/check-duplication.swagger.ts
- apps/server/src/users/swagger/create-user.swagger.ts
- swagger api 문서의 경로를 다음과 같이 수정하였습니다
변경 전 ```api-docs```
변경 후 ```api/docs```
- close #45
> chore: update swagger setting

- .github/workflows/deploy.yml
- CD script에 pnpm build를 추가해서 원활하게 프로덕션 모드로 실행할 수 있게 했습니다.
- #17
> fix: add pnpm build

- apps/client/src/components/FeatureCard.tsx
- apps/client/src/components/Header.tsx
- apps/client/src/components/modal/CreateSessionModal.tsx
- apps/client/src/components/modal/InputField.tsx
- apps/client/src/components/modal/SignInModal.tsx
- apps/client/src/components/modal/SignUpModal.tsx
- apps/client/src/index.css
- apps/client/src/pages/Home.tsx
- apps/client/tailwind.config.js
- 폰트가 미적용되던 문제를 수정했습니다.
- 기존에 폰트를 불러오는 부분이 누락되어 추가했습니다.
- 기본 폰트를 `Pretendard` 폰트로 변경했습니다.
- close #51
> fix(fe): resolve font unapplied issue

- apps/server/prisma/migrations/20241111022352_init/migration.sql
- apps/server/prisma/schema.prisma
- ERD를 보고 prisma schema에 모든 테이블을 세팅했습니다.
- close #56
> feat(be): add prisma model

- apps/server/prisma/migrations/20241111063729_init/migration.sql
- apps/server/prisma/schema.prisma
> feat(be): add prisma model relation

- apps/client/src/components/modal/InputField.tsx
- apps/client/src/components/modal/SignInModal.tsx
- apps/client/src/components/modal/SignUpModal.tsx
- apps/client/src/features/auth/auth.hook.ts
- 회원 가입시 일부 누락된 정책 검증을 추가했습니다.
- 이메일
- 이메일 형식 체크
- 이메일 공백 금지
- 닉네임
- 닉네임 공백 금지
- 이메일, 닉네임 중복 확인 요청 후 응답이 도착 전에, 변경이 되면 해당 요청을 취소하거나 이전 값으로 덮어 씌웁니다.
- close #68
> feat(fe): enhance validation logic

- apps/client/src/features/auth/auth.api.ts
- apps/client/vite.config.ts
- 프록시 설정을 위한 Vite 설정 파일을 수정하고, 이를 적용하는 작업을 추가했습니다.
- close #76
> feat(fe): update Vite config for proxy settings

- apps/client/src/components/index.ts
> fix(fe): resolve build error

- apps/client/src/components/index.ts
- apps/client/src/components/modal/CreateQuestionModal.tsx
- apps/client/src/components/modal/CreateReplyModal.tsx
- apps/client/src/components/qna/QuestionDetail.tsx
- apps/client/src/components/qna/QuestionList.tsx
- 질문에 대한 답변 생성을 위한 모달을 추가했습니다.
- close #79
> feat(fe): implement reply modal for reply creation

- apps/client/src/components/modal/SignInModal.tsx
- apps/client/src/components/modal/SignUpModal.tsx
- apps/client/src/features/user/user.hook.ts
- 로그인 버튼이 허용되지 않는 조건에서도 로그인 버튼이 클릭되는 현상을 수정했습니다.
- 기존에는 허용되지 않는 조건에서는 UI에서는 표현해주나, 기능적으로는 로그인 요청이 가능했습니다.
- close #95
> fix(fe): disable login button when not allowed

- apps/server/src/replies/dto/create-reply.dto.ts
- apps/server/src/replies/dto/delete-reply.dto.ts
- apps/server/src/replies/dto/update-reply.dto.ts
- apps/server/src/replies/replies.controller.ts
- apps/server/src/sessions/sessions.service.ts
- reply의 DTO들을 base DTO를 사용하는 방향으로 리팩토링 해주었습니다.
> refactor(be): apply base dto

- apps/client/src/components/modal/CreateQuestionModal.tsx
- apps/client/src/components/modal/CreateReplyModal.tsx
- 질문하기, 답변하기 모달의 높이가 일부 기기에서 가려지던 문제를 수정했습니다.
- close #105
> fix(fe): adjust modal height for CreateQuestionModal and CreateReplyModal

- apps/server/src/replies/replies.controller.ts
- apps/server/src/replies/replies.module.ts
- apps/server/src/replies/replies.service.ts
- apps/server/src/replies/swagger/create-reply.swagger.ts
- apps/server/src/sessions-auth/sessions-auth.repository.ts
- apps/server/src/sessions/sessions.module.ts
- apps/server/src/sessions/sessions.repository.ts
- apps/server/src/sessions/sessions.service.ts
- 답변을 생성할 시에, 해당 답변을 단 사람이 session의 host인지를 확인하는 기능을 구현했습니다.
- 다음과 같이 응답합니다 :
```js
{
"type": "success",
"data": {
"reply_id": 15,
"is_host": false
}
}
```
- close #82
> feat(be): verify reply host

- apps/server/src/questions/questions.repository.ts
- 질문과 답변의 데이터가 id 순으로 정렬되지 않은 버그를 해결하였습니다.
> fix(be): fix question, reply order bug

- apps/client/src/components/qna/QuestionList.tsx
- apps/client/src/routes/session.$sessionId.tsx
- 질문 목록 내 구분선 렌더링 로직을 변경했습니다.
- 세션 토큰 획득 실패시 홈으로 라우팅 로직을 추가했습니다.
> fix(fe): update rendering logic and handle session token retrieval error

- apps/server/src/questions/questions.controller.ts
- apps/server/src/questions/questions.service.ts
> fix(be): add session expired state

- apps/client/src/components/qna/QuestionItem.tsx
- apps/client/src/components/qna/ReplyItem.tsx
- 좋아요 API의 반환 값을 사용하도록 수정했습니다.
> fix(fe): apply like toggle API response

- apps/client/package.json
- apps/client/src/components/qna/QuestionDivider.tsx
- apps/client/src/components/qna/QuestionList.tsx
- apps/client/src/components/qna/QuestionSection.tsx
- pnpm-lock.yaml
- 각 질문의 특징에 따라 나뉘는 섹션을 가시적으로 쉽게 볼 수 있게 변경했습니다.
- 질문이 길어지는 것을 염두에 두어, 펼치기/줄이기 기능을 추가했습니다.
- closed #136
> feat(fe): implement togglable question sections with expand/collapse animations

- apps/client/package.json
- apps/client/src/components/FeatureCard.tsx
- apps/client/src/components/qna/QuestionDetail.tsx
- apps/client/src/components/qna/QuestionDivider.tsx
- apps/client/src/components/qna/QuestionItem.tsx
- apps/client/src/components/qna/QuestionList.tsx
- apps/client/src/components/qna/ReplyItem.tsx
- apps/client/src/features/session/qna/qna.dto.ts
- apps/client/src/features/session/session.slice.ts
- apps/client/src/pages/HomePage.tsx
- apps/client/src/routes/session.$sessionId.tsx
- pnpm-lock.yaml
- 기존 이모지로 사용되던 부분을 아이콘으로 변경했습니다.
- 세션 화면에서 세션 타이틀을 확인할 수 있습니다.
- 호스트의 답변을 표시하고, 호스트의 답변을 상단에 배치합니다.
- 질문 섹션의 토글 버튼의 클릭 영역을 확장했습니다.
- close #140
> feat(fe): UI/UX improvement

- apps/server/src/socket/socket.gateway.ts
> fix(be): socket exception handling

- apps/server/src/questions/questions.controller.ts
- apps/server/src/socket/socket.gateway.ts
- question에 스팰링 에러가 있어서 해결하였습니다.
> fix(be): socket spelling error

- apps/client/package.json
- apps/client/src/features/session/qna/qna.type.ts
- apps/client/src/features/socket/index.ts
- apps/client/src/features/socket/socket.service.ts
- apps/client/src/features/socket/socket.type.ts
- apps/client/src/routes/session/route.tsx
- apps/client/src/vite-env.d.ts
- pnpm-lock.yaml
- 실시간 처리를 위한 소켓 서비스를 추가했습니다.
- 이벤트와 이벤트에 따른 페이로드 타입을 추가했습니다.
- 이벤트에 따른 응답 액션을 추가했습니다.
- 웹소켓 연결 관련하여 nginx 설정을 변경했습니다.
- close #149
> feat(fe): implement SocketService for real-time event handling

- apps/server/src/app.module.ts
- apps/server/src/chats/chats.module.ts
- apps/server/src/chats/chats.repository.ts
- apps/server/src/chats/chats.service.ts
- apps/server/src/socket/socket.gateway.ts
- apps/server/src/socket/socket.module.ts
- apps/server/tsconfig.json
- 채팅 메시지를 데이터베이스에 저장할 수 있는 기능을 구현하였습니다.
- 채팅 메시지를 생성할 때 닉네임도 함께 반환할 수 있도록 하였습니다.
- close #124
- close #135
> feat(be): chatting

- apps/server/src/app.module.ts
- apps/server/src/socket/socket.gateway.ts
- 이벤트 메시지를 커스텀 이벤트로 보내도록 바꿨습니다.
> fix(be): custom message

- apps/client/package.json
- apps/client/src/components/qna/ChattingList.tsx
- apps/client/src/components/qna/ChattingMessage.tsx
- apps/client/src/components/qna/QuestionDetail.tsx
- apps/client/src/components/qna/QuestionDivider.tsx
- apps/client/src/components/qna/QuestionList.tsx
- apps/client/src/components/qna/QuestionSection.tsx
- apps/client/src/features/session/chatting/chatting.type.ts
- apps/client/src/features/socket/index.ts
- apps/client/src/features/socket/socket.context.tsx
- apps/client/src/features/socket/socket.hook.ts
- apps/client/src/features/socket/socket.service.ts
- apps/client/src/features/socket/socket.type.ts
- apps/client/src/routes/session/route.tsx
- apps/client/tailwind.config.js
- pnpm-lock.yaml
- 채팅 송수신 이벤트 및 타입 정의를 진행했습니다.
- 채팅 송수신 이벤트에 따라 이벤트 처리를 진행했습니다.
- 세션 중복 접속 금지 기능을 추가했습니다.
- 이전 접속 세션에서 세션 접속이 종료됩니다.
- close #154
> feat(fe): implement socket-based chat messaging system

- apps/client/src/components/modal/CreateQuestionModal.tsx
- apps/client/src/components/modal/CreateReplyModal.tsx
- apps/client/src/components/qna/ChattingList.tsx
- apps/client/src/features/socket/socket.service.ts
- 질문생성, 답변생성 모달의 높이를 조절했습니다.
- 소켓의 응답으로 전달되는 응답 중 불필요한 일부 요소를 제거했습니다.
> fix(fe): remove unused properties and adjust modal heights

- apps/client/src/components/modal/CreateSessionModal.tsx
- apps/client/src/components/qna/ChattingList.tsx
- 채팅 리스트에서 스크롤시 최하단으로 움직이는 버튼을 추가했습니다.
- 세션 생성시 정책에 위반되면 경고 메시지를 표시합니다.
- close #160 
- close #161
> feat(fe): UX improvements

- apps/client/src/components/qna/ChattingList.tsx
- 사파리에선 스크롤 종료 이벤트가 지원되지 않아, 해당 부분을 구현하여 추가했습니다.
> feat(fe): add Safari browser support for scrollend event

- apps/server/package.json
- apps/server/src/app.module.ts
- apps/server/src/common/filters/global-exception.filter.ts
- apps/server/src/common/filters/http-exception.filter.ts
- apps/server/src/common/middlewares/http-logger.middleware.ts
- apps/server/src/logger/logger.module.ts
- apps/server/src/logger/logger.service.ts
- apps/server/src/logger/winston.config.ts
- apps/server/src/main.ts
- apps/server/src/socket/socket.gateway.ts
- apps/server/src/socket/socket.module.ts
- apps/server/tsconfig.json
- pnpm-lock.yaml
-  원활한 모니터링을 위한 로거를 만들고 적용했습니다.
- close #169
> feat(be): set http logger and connection logger

- apps/server/package.json
- apps/server/src/socket/socket.gateway.ts
- pnpm-lock.yaml
- turbo.json
- 소켓이 연결되는 순간과 끊어지는 순간에 참여자수를 브로드캐스팅 하도록 했습니다.
- 소켓이벤트들을 상수로 관리하도록 변경했습니다.
- close #171
> feat(be): add socket event that broadcasts participants count in session

- apps/server/package.json
- apps/server/src/users/users.service.ts
- pnpm-lock.yaml
- 다음과 같은 불명확한 `nickname`을 `user`로 변경하였습니다.
```ts
//기존 코드
async hasNickname(nickname: string) {
return this.userRepository.findByNickname(nickname).then((nickname) => !!nickname);
}
```
```ts
//변경 코드
async hasNickname(nickname: string) {
return this.userRepository.findByNickname(nickname).then((user) => !!user);
}
```
> fix(be): rename callback parameter in hasNickname from 'nickname' to 'user'

- apps/server/src/users/dto/check-email.dto.ts
- apps/server/src/users/dto/check-nickname.dto.ts
- apps/server/src/users/users.controller.ts
- user의 nickname, email 중복 확인 로직에 nickname, email의 validation 로직을 추가해주었습니다.
> fix(be): add user validation DTO

- apps/client/src/components/qna/ChattingList.tsx
- apps/client/src/components/qna/ReplyItem.tsx
- apps/client/src/features/user/user.api.ts
- 채팅에서 유저 스크롤 핸들링 로직을 개선했습니다.
- 호스트 표시에 메인 색상을 적용했습니다.
- 닉네임 중복 검사시, 인코딩하여 값을 전달합니다.
- close #166
> fix(fe): improve user scroll handling logic in chatting

- apps/client/src/components/modal/CreateSessionModal.tsx
- 세션 이름 검증 조건이 변경되었습니다.
- close #173
> fix(fe): update session name validation rules

- apps/client/src/components/modal/CreateQuestionModal.tsx
- apps/client/src/components/modal/CreateReplyModal.tsx
- apps/client/src/components/modal/CreateSessionModal.tsx
- apps/client/src/components/modal/SignInModal.tsx
- apps/client/src/components/modal/SignUpModal.tsx
- 여러 모달에 걸쳐 버튼들의 순서를 재조정했습니다.
- close #174
> fix(fe): adjust button order

- apps/server/prisma/migrations/20241126054534_init/migration.sql
- apps/server/prisma/migrations/20241126060448_add_is_host_mapping/migration.sql
- apps/server/prisma/schema.prisma
- apps/server/src/questions/questions.service.ts
- apps/server/src/replies/replies.controller.ts
- apps/server/src/replies/replies.service.ts
- apps/server/src/sessions-auth/dto/update-host.dto.ts
- apps/server/src/sessions-auth/sessions-auth.controller.ts
- apps/server/src/sessions-auth/sessions-auth.module.ts
- apps/server/src/sessions-auth/sessions-auth.repository.ts
- apps/server/src/sessions-auth/sessions-auth.service.ts
- apps/server/src/sessions-auth/swagger/sessions-host.swagger.ts
- apps/server/src/sessions-auth/swagger/sessions-user.swagger.ts
- apps/server/src/sessions/sessions.module.ts
- apps/server/src/sessions/sessions.repository.ts
- apps/server/src/sessions/sessions.service.ts
- pnpm-lock.yaml
- multi host 기능을 추가하였습니다.
- session에 참여중인 user들을 조회하는 기능을 만들었습니다.
- user에게 host 권한을 조정하는 기능을 추가했습니다.
- 슈퍼 호스트가 아닌 사람이 host 권한 조정을 하는 경우에 대한 예외 처리를 추가했습니다.
- 관련 swagger 문서를 추가했습니다.
- close #178
> feat(be): multi host

- apps/client/src/features/toast/ToastMessage.tsx
- 토스트 메시지의 프로그레스 바를 제거했습니다.
- close #183
> fix(fe): simplify ToastMessage component

- apps/server/src/auth/auth.controller.ts
- `refreshtToken`이라고 작성된 오타를 발견하여 수정하였습니다.
> fix(be): correct 'refreshtToken' typo

- apps/server/src/auth/auth.controller.ts
- apps/server/src/auth/auth.service.ts
- apps/server/src/auth/swagger/login.swagger.ts
- token 재발급 response에 userId 필드를 추가했습니다.
> refactor(be): add userId in refresh token response

- apps/server/src/questions/questions.service.ts
- host validation 관련하여 pinned 및 closed 권한 오류를 수정했습니다.
> fix(be): host validation

- apps/client/src/components/Button.tsx
- apps/client/src/components/qna/QuestionList.tsx
- apps/client/src/components/qna/SessionSettingsDropdown.tsx
- apps/client/src/features/user/user.api.ts
- apps/client/src/features/user/user.hook.ts
- apps/client/src/shared/validation/validation-status.util.ts
- 회원 가입에서 검증 로직을 업데이트 했습니다.
- 기존 프론트엔드에서 검증하던 부분을 백엔드로 위임했습니다.
- 추가로, 질문 목록에서 드롭다운이 보이는 상태에서 설정을 다시 누르면, 닫혔다 열리는 현상을 수정했습니다.
- close #176
> fix(fe): modify validation logic for signup process

- apps/client/src/components/modal/CreateSessionModal.tsx
- apps/client/src/components/modal/SignInModal.tsx
- apps/client/src/components/modal/SignUpModal.tsx
- apps/client/src/components/qna/QuestionList.tsx
- 세션 공유 기능을 추가했습니다.
- 질문 목록에서 설정에서 공유 버튼을 클릭시, 클립보드로 링크를 복사합니다.
- 회원가입, 로그인, 세션 생성 모달에서의 로고를 헤더와 동일하게 변경했습니다.
- close #200
> feat(fe): add session sharing

- apps/client/.eslintrc.json
- apps/client/src/components/Button.tsx
- apps/client/src/routes/my.tsx
- apps/client/src/routes/session/$sessionId/$questionId/index.tsx
- apps/client/src/routes/session/$sessionId/index.tsx
- apps/client/src/routes/session/route.tsx
- 세션에 포함되지 않은 질문에 접근시, 라우팅을 금지합니다.
- 세션에 포함되지 않은 질문에 접근시, 질문 목록으로 이동합니다.
- 만약, 존재하지 않는 세션이라면 홈으로 이동합니다.
- Button 컴포넌트 ref 관련한 에러 로그가 발생하여서, forwardRef로 변경했습니다.
- close #199
> fix(fe): prevent invalid routing

- apps/client/package.json
- apps/client/src/features/auth/auth.dto.ts
- apps/client/src/features/session/qna/qna.dto.ts
- apps/client/src/features/session/qna/qna.type.ts
- apps/client/src/features/session/session.dto.ts
- apps/client/src/features/session/session.type.ts
- apps/client/src/features/socket/socket.service.ts
- apps/client/src/features/socket/socket.type.ts
- apps/client/src/features/user/user.dto.ts
- pnpm-lock.yaml
- 'zod' 라이브러리를 여러 데이터 송수신에서 유효성을 검사하기 위해 추가했습니다.
- API 요청시, 정책상 필요한 데이터 유효성 검사를 실시합니다.
- API 수신 데이터, 소켓 통신에서의 페이로드 데이터 유효성 검사를 실시합니다.
- close #206
> feat(fe): add zod library for request/response/socket-payload validation

- apps/server/src/chats/chats.controller.ts
- apps/server/src/chats/chats.module.ts
- apps/server/src/chats/chats.service.ts
- apps/server/src/chats/swagger/get-chats.swagger.ts
- apps/server/src/questions/questions.service.ts
- apps/server/src/sessions-auth/sessions-auth.service.ts
- 채팅 리스트 조회 기능을 구현했습니다.
- 채팅 리스트 조회 관련한 swagger 문서를 업데이트 했습니다.
- 세션 생성자가 스스로의 권한을 박탈하는 경우에 대한 예외처리도 추가했습니다.
- close #203 
- close #204
> feat(be): chatting list

- apps/client/src/components/qna/ChattingList.tsx
- apps/client/src/features/session/chatting/chatting.api.ts
- apps/client/src/features/session/chatting/chatting.dto.ts
- apps/client/src/features/session/chatting/chatting.slice.ts
- apps/client/src/features/session/chatting/chatting.type.ts
- apps/client/src/features/session/chatting/index.ts
- apps/client/src/routes/session/$sessionId/$questionId/index.tsx
- apps/client/src/routes/session/$sessionId/index.tsx
- 이전 채팅 목록을 불러오는 기능을 추가했습니다.
- 채팅의 최상단으로 이동하면 자동으로 불러옵니다.
- close #209
> feat(fe): load previous chattings

- apps/server/src/common/guards/session-token-validation.guard.ts
- apps/server/src/sessions/dto/terminate-session.dto.ts
- apps/server/src/sessions/sessions.controller.ts
- apps/server/src/sessions/sessions.module.ts
- apps/server/src/sessions/sessions.repository.ts
- apps/server/src/sessions/sessions.service.ts
- apps/server/src/sessions/swagger/terminate-session.swagger.ts
- apps/server/src/socket/socket.gateway.ts
- 세션 생성자가 세션을 만료시킬 수 있는 기능을 추가하였습니다.
- 세션 만료 시에 소켓으로 브로드캐스트 되도록 하였습니다.
- 관련하여 swagger를 업데이트 했습니다.
- close #210
> feat(be): add session termination

- apps/client/src/components/qna/ChattingList.tsx
- apps/client/src/features/auth/auth.api.ts
- apps/client/src/features/session/chatting/chatting.api.ts
- apps/client/src/features/session/qna/qna.api.ts
- apps/client/src/features/session/qna/qna.type.ts
- apps/client/src/features/session/session.api.ts
- apps/client/src/features/socket/socket.service.ts
- apps/client/src/features/socket/socket.type.ts
- apps/client/src/features/user/user.api.ts
- 'zod'를 이용한 검증 로직을 추가했습니다.
- 채팅 페이지네이션에서 의존 배열 문제를 수정했습니다.
- close #212
> feat(fe): add validation logic using zod

- apps/client/src/components/qna/QuestionItem.tsx
- apps/client/src/components/qna/ReplyItem.tsx
- 호스트의 경우, 조건에 상관 없이 질문/답변을 지우는 권한이 추가되었습니다.
- close #220
> feat(fe): add question and reply item delete action for host users

- apps/server/src/sessions/sessions.repository.ts
- 내가 참여한 세션 기록을 불러오는 경우 생성일 기준 내림차순으로 정렬되도록 하였습니다. 
- (제일 최근에 생성된 세션이 제일 위로 올라가도록 하였습니다.)
> fix(be): sort session history in descending order

- apps/client/src/components/modal/SessionParticipantsModal.tsx
- apps/client/src/features/auth/auth.api.ts
- apps/client/src/features/auth/auth.hook.ts
- 로그인 관련 이슈를 해결했습니다.
- 호스트 권한 변경시, 화면에 실시간으로 적용되지 않던 문제를 해결했습니다.
> fix(fe): apply feedback

- apps/client/src/components/modal/SessionParticipantsModal.tsx
- 권한 수정시 발생하는 오류에 대해 알림을 추가했습니다.
> feat(fe): add notification about permission errors

- apps/client/src/components/modal/CreateQuestionModal.tsx
- apps/client/src/components/modal/CreateReplyModal.tsx
- apps/client/src/components/qna/QuestionList.tsx
> feat(fe): include question content in reply modal

- apps/client/src/components/modal/CreateQuestionModal.tsx
- apps/client/src/components/modal/CreateReplyModal.tsx
- 질문 생성 모달, 답변 생성 모달 최대 높이, 최소 높이를 설정하여 텍스트 길이에 따른 스타일을 일치화했습니다.
> fix(fe): adjust modal style

- apps/client/src/shared/axios.config.ts
- axios 인터셉터 설정에서 API 응답 값을 과거 형식으로 되어있어 수정했습니다.
> fix(fe): update axios interceptor

- apps/server/package.json
- apps/server/src/chats/chats.repository.ts
- apps/server/src/chats/chats.service.spec.ts
- apps/server/src/chats/chats.service.ts
- apps/server/src/questions/questions.service.spec.ts
- apps/server/src/replies/replies.service.spec.ts
- apps/server/src/sessions-auth/sessions-auth.service.spec.ts
- apps/server/src/sessions/sessions.service.spec.ts
- 서비스레이어에 모킹을 활용해서 테스트코드를 추가했습니다.
- close #234
> test: add service test with mocking

- .github/workflows/test.yml
- apps/client/.eslintrc.json
- apps/client/.gitignore
- apps/client/package.json
- apps/client/playwright.config.ts
- apps/client/src/components/Button.tsx
- apps/client/src/components/modal/SignInModal.tsx
- apps/client/src/components/modal/SignUpModal.tsx
- apps/client/src/routes/session/$sessionId/index.tsx
- apps/client/tests/HomePage.spec.ts
- apps/client/tests/MyPage.spec.ts
- apps/client/tests/QnADetailPage.spec.ts
- apps/client/tests/QnAPage.spec.ts
- apps/client/tsconfig.app.json
- package.json
- pnpm-lock.yaml
- turbo.json
- Playwright 이용 테스트 코드를 추가했습니다.
- 랜딩페이지
- 마이 세션 페이지
- Q&A 페이지
- 테스트 CI 코드를 추가했습니다.
- close #237
> test(fe): add playwright tests

- .github/workflows/test.yml
- apps/server/src/questions/questions.service.spec.ts
- package.json
> chore: modify test workflow file

- apps/client/package.json
- apps/client/playwright.config.ts
- apps/client/tests/QnADetailPage.spec.ts
- apps/client/tests/QnAPage.spec.ts
> test(fe): change config file

- apps/server/prisma/migrations/20241203042135_add_session_id_index_in_chatting/migration.sql
- apps/server/prisma/migrations/20241203043418_add_session_id_chatting_id_composite_indexx/migration.sql
- apps/server/prisma/migrations/20241203052414_modify_chatting_index/migration.sql
- apps/server/prisma/migrations/20241203052615_modify_chatting_composite_index_desc/migration.sql
- apps/server/prisma/migrations/20241203053124_add_question_session_id_index/migration.sql
- apps/server/prisma/schema.prisma
DB에 index를 추가하여 성능을 개선하였습니다.
- close #243
> feat(be): add database index

- .github/workflows/deploy.yml
> fix: update deploy.yml
