boostcampwm-2024/web07-Ask-It

pnpm-workspace.yaml
- 루트 디렉토리에 pnpm-workspace 파일이 누락되어 백엔드 개발 브랜치에 해당 파일을 추가했습니다.
- #8
=> chore: add missing pnpm-workspace.yaml file

.github/workflows/lint-format.yml, apps/client/src/features/modal/components/Background.tsx, apps/client/src/features/modal/index.ts, apps/client/src/features/modal/modal.context.ts, apps/client/src/features/modal/modal.hook.tsx
- 모달을 사용하기 위해 아래 내용을 추가했습니다.
- 모달을 관리하는 Context 추가
- 모달을 생성하고 접근할 수 있는 커스텀 훅 추가
- 브랜치 이름에 괄호를 추가하여, 깃헙 액션에 오류가 발생하여 해당 부분 수정합니다.
- close #25
=> feat(fe): add modal management context and custom hook

apps/client/src/features/session/chatting/chatting.slice.ts, apps/client/src/features/session/chatting/chatting.type.ts, apps/client/src/features/session/chatting/index.ts, apps/client/src/features/session/index.ts, apps/client/src/features/session/qa/index.ts, apps/client/src/features/session/qa/qa.slice.ts, apps/client/src/features/session/qa/qa.type.ts, apps/client/src/features/session/session.slice.ts, apps/client/src/features/session/session.store.ts, apps/client/src/features/session/session.type.ts
- Q&A의 질문 및 답변 전역 상태 관리를 위한 타입과 액션을 추가했습니다.
- 채팅 전역 상태 관리를 위한 타입과 액션을 추가했습니다.
- 데이터들의 타입은 임시로 ERD을 참고하여 작성했습니다. 이후에 제공되는 DTO에 따라 수정하는 방식으로 진행하거나, 어댑터를 추가하여 진행하겠습니다.
- close #27
=> feat(fe): add chat and Q&A management slices with session store

.github/workflows/deploy.yml
=> fix: modify CI/CD

.github/workflows/lint-format.yml
- lint-format.yml에서 pull_request 대상 브랜치 중 `develop-be` `develop-fe` 없앴습니다.
- 도메인(fe/be)을 설정하기 애매해서 일단 없는 상태로 작성했습니다.
- close #38
=> refactor: remove develop branches from PR workflow

apps/server/package.json, apps/server/src/main.ts, apps/server/src/users/dto/create-user.dto.ts, apps/server/src/users/dto/validate-user.dto.ts, apps/server/src/users/swagger/check-duplication.swagger.ts, apps/server/src/users/swagger/create-user.swagger.ts, apps/server/src/users/users.controller.ts, pnpm-lock.yaml, prisma/schema.prisma
- swagger를 세팅하여 api 문서화를 하였습니다
- main.ts에 swagger를 설정하였습니다. 다음의 주소로 swagger 문서확인이 가능합니다
```localhost:3000/api-docs```
- controller에 적용된 swagger를 확장성을 고려해 별도의 폴더와 파일로 구분하였습니다
- dto에 적용된 swagger는 가독성과 안정성을 고려해 분리하지 않고 함께 두었습니다.
- close #42
=> feat(be): swagger setting

apps/server/package.json, apps/server/prisma/migrations/20241109165716_init/migration.sql, apps/server/prisma/migrations/20241109170330_init/migration.sql, apps/server/prisma/migrations/20241109170857_init/migration.sql, apps/server/prisma/migrations/20241109181624_init/migration.sql, apps/server/prisma/migrations/20241110141915_init/migration.sql, apps/server/prisma/migrations/20241110152007_init/migration.sql, apps/server/prisma/migrations/20241110160147_init/migration.sql, apps/server/prisma/migrations/20241110160251_init/migration.sql, apps/server/prisma/migrations/20241110160419_init/migration.sql, apps/server/prisma/schema.prisma, apps/server/src/app.module.ts, apps/server/src/sessions-auth/dto/session-auth.dto.ts, apps/server/src/sessions-auth/sessions-auth.controller.spec.ts, apps/server/src/sessions-auth/sessions-auth.controller.ts, apps/server/src/sessions-auth/sessions-auth.module.ts, apps/server/src/sessions-auth/sessions-auth.repository.ts, apps/server/src/sessions-auth/sessions-auth.service.spec.ts, apps/server/src/sessions-auth/sessions-auth.service.ts, apps/server/src/sessions-auth/swagger/sessions-auth.swagger.ts, apps/server/src/sessions/sessions.service.ts, pnpm-lock.yaml
- session-user 사이의 토큰 발급 및 검사 기능을 구현했습니다.
- prisma에서는 model을 자동으로 camelCase로 바꾸는 것을 확인했습니다. 이에 따라 ERD 상의 User_Session_Token 테이블 명을 UserSessionToken으로 변경하였습니다.
(+repository에서 해당 모델을 참조할 때는 userSessionToken으로 참조합니다.(this.prisma.userSessionToken))
예외처리하는 기준을 클라이언트가 토큰을 무단으로 수정, 삭제, 생성 한 경우에 대해서 처리하였습니다. 예외처리 방법은 해당 이슈에 기록해놓았습니다.
추후 예외처리가 더 필요할 경우 추가로 구현하겠습니다.
- close #37
=> Feat(be): user session token

apps/server/prisma/migrations/20241110160251_init/migration.sql, apps/server/src/app.module.ts, apps/server/src/questions/dto/create-question.dto.ts, apps/server/src/questions/dto/get-question.dto.ts, apps/server/src/questions/questions.controller.spec.ts, apps/server/src/questions/questions.controller.ts, apps/server/src/questions/questions.module.ts, apps/server/src/questions/questions.repository.ts, apps/server/src/questions/questions.service.spec.ts, apps/server/src/questions/questions.service.ts, apps/server/src/questions/swagger/create-question.swagger.ts, apps/server/src/questions/swagger/get-question.swagger.ts
- 렌더링에 필요한 세션에 맞는 디테일을 가진 질문 데이터를 가져오는 GET API를 만들었습니다.
- 사용자가 질문을 생성하기 위한 POST API를 만들었습니다.
- close #59
=> feat(be): add create question and read questions api

apps/client/src/features/auth/auth.hook.ts
- 에러가 전파되지 않아 UI가 업데이트되지 않던 문제를 수정했습니다.
=> fix(fe): propagate error in useSignInForm hook

apps/client/src/components/modal/InputField.tsx, apps/client/src/components/modal/SignInModal.tsx
- 로그인시 비밀번호 입력 후 엔터 입력으로 로그인을 시도할 수 있게 추가했습니다.
=> feat(fe): add onKeyDown prop to InputField and handle Enter key in SignInModal

apps/server/src/common/guards/session-token-validation.guard.ts
- 로그인 사용자가 세션토큰가드를 통과하지 못하는걸 발견하고 수정했습니다. 
- #75
=> fix(be): fix validation logic

apps/server/src/sessions-auth/sessions-auth.repository.ts
=> fix(be): return only the token from new user session creation

apps/client/.eslintrc.json, apps/client/src/components/Header.tsx, apps/client/src/components/modal/CreateSessionModal.tsx, apps/client/src/components/my/SessionRecord.tsx, apps/client/src/features/auth/auth.store.ts, apps/client/src/features/session/index.ts, apps/client/src/features/session/session.api.ts, apps/client/src/features/session/session.dto.ts, apps/client/src/pages/MyPage.tsx, apps/client/src/pages/QnAPage.tsx, apps/client/src/routes/__root.tsx, apps/client/src/routes/my.tsx, apps/client/src/routes/session.$sessionId.tsx
- 세션과 관련된 API 연동 작업을 진행했습니다.
- 세션 생성 후 해당 세션으로 이동합니다.
- 비어있는 세션 이름으론 생성할 수 없습니다.
- 마이페이지에서 참여한 세션을 조회할 수 있습니다.
- 비 로그인 상태에서 마이페이지로 접속하면 메인 페이지로 리다이렉트합니다.
- 참여한 세션을 클릭하면 해당 세션으로 접속합니다.
- Q&A 세션에 접속하면 세션 토큰 발급 API를 통해 세션에 맞는 토큰을 가져옵니다.
- 토큰 발급 API 내부에서 스토리지로부터 불러오기, 저장 로직을 추가합니다.
- 페이지 로딩 전, 로그인 여부를 판단하고 렌더링을 진행하는 방식으로 변경했습니다.
- close #111
=> feat(fe): integrate session API

apps/client/src/components/modal/CreateQuestionModal.tsx, apps/client/src/components/modal/CreateReplyModal.tsx, apps/client/src/components/qna/QuestionItem.tsx, apps/client/src/components/qna/ReplyItem.tsx, apps/client/src/features/auth/auth.hook.ts, apps/client/src/routes/session.$sessionId.tsx
- 유저의 액션에 따라 토스트 메시지를 이용한 피드백을 추가했습니다.
- 세션 접속시 토스트 메시지를 이용한 피드백을 추가했습니다.
- 질문 생성, 수정, 삭제와 같은 여러 액션에 대해 성공 피드백을 추가했습니다.
- 답변 생성, 수정, 삭제에 대해 성공 피드백을 추가했습니다.
- 로그인시 위치에 따른 새로고침 로직을 추가했습니다.
- close #127
=> feat(fe): add toast feedback

apps/client/src/components/modal/CreateQuestionModal.tsx, apps/client/src/components/modal/CreateReplyModal.tsx, apps/client/src/components/modal/CreateSessionModal.tsx, apps/client/src/components/modal/SignInModal.tsx, apps/client/src/components/modal/SignUpModal.tsx, apps/client/src/components/qna/QuestionItem.tsx, apps/client/src/components/qna/ReplyItem.tsx, apps/client/src/features/auth/auth.hook.ts
- 중복된 요청을 금지합니다.
- 서버로부터 응답을 받기 전 클라이언트가 재요청할 수 없도록 수정했습니다.
- 좋아요 기능의 경우에는 1초에 1번만 요청할 수 있게 수정했습니다.
- close #164
- close #167
=> feat(fe): prevent duplicate api requests

apps/client/src/components/index.ts, apps/client/src/components/modal/Participant.tsx, apps/client/src/components/modal/SessionParticipantsModal.tsx, apps/client/src/components/qna/ChattingList.tsx, apps/client/src/features/toast/ToastContainer.tsx, apps/client/src/features/toast/ToastMessage.tsx
- 멀티 호스트를 위한 UI를 구현했습니다.
- 현재 더미 데이터를 이용하여 구현되어있습니다.
- 토스트 메시지가 모달이 보여질 때 가려지는 현상을 수정했습니다.
<div align='center'>
</div>
- close #186
=> feat(fe): implement multi-host ui

apps/client/src/components/qna/ChattingList.tsx, apps/client/src/components/qna/QuestionDetail.tsx, apps/client/src/components/qna/QuestionList.tsx, apps/client/src/index.css, apps/client/src/pages/MyPage.tsx
- 운영체제별 일관되지 않은 스크롤바를 이유로 제거했던 스크롤바를 커스텀하여 추가했습니다.
- 세션 기록, 질문 목록, 상세 질문, 채팅창에 새롭게 적용되었습니다.
- 기본 스크롤이 더 낫다고 판단되면 제거할 예정입니다.
- 사용자 경험을 위해 드래그 금지를 해제했습니다.
- 윈도우즈의 경우, 채팅창에서 가로 스크롤이 확인되었던 것이 현재 개발 환경에서 확인이 불가하여, 추후에 확인 바랍니다.
<div align='center'>
</div>
- close #190
=> feat(fe): custom scroll bar

apps/client/src/components/modal/CreateReplyModal.tsx
- 빌드 에러를 수정했습니다.
- 기존 optional 조건을, nullable로 변경 후 null을 포함하지 않은 오류가 발생하여 추가했습니다.
=> fix(fe): include userId in reply addition for CreateReplyModal

apps/client/src/components/modal/SessionTerminateModal.tsx, apps/client/src/components/qna/QuestionList.tsx, apps/client/src/features/session/session.api.ts, apps/client/src/features/session/session.dto.ts, apps/client/src/features/socket/socket.service.ts
- 세션 종료를 추가했습니다.
- 설정의 세션 종료 버튼을 클릭시, 세션을 종료하고 다른 유저들에게 브로드캐스트됩니다.
- close #216
=> feat(fe): implement session termination

apps/server/prisma/migrations/20241128045519_add_on_delete_cascade_to_reply_question/migration.sql, apps/server/prisma/schema.prisma, apps/server/src/questions/questions.controller.ts, apps/server/src/questions/questions.service.ts, apps/server/src/replies/replies.controller.ts, apps/server/src/replies/replies.service.ts
- 호스트가 모든 질문/답변을 삭제시킬 수 있는 기능을 구현하였습니다.
- close #215
=> feat(be): power deletion

apps/client/src/components/modal/DeleteConfirmModal.tsx, apps/client/src/components/qna/QuestionDetail.tsx, apps/client/src/components/qna/QuestionItem.tsx, apps/client/src/components/qna/QuestionList.tsx, apps/client/src/components/qna/ReplyItem.tsx, apps/client/src/components/qna/SessionSettingsDropdown.tsx, apps/client/src/features/socket/socket.service.ts
- 세션 종료 버튼의 색상을 수정했습니다.
- 질문과 답변이 비어있는 경우 UI를 추가했습니다.
- 질문과 답변 삭제시, 모달을 통해 다시 한 번 확인 받도록 수정했습니다.
- 세션 종료시 소켓 연결을 끊도록 수정했습니다.
- close #222
=> feat(fe): change styles

apps/server/src/auth/auth.service.ts, apps/server/src/auth/jwt-auth.guard.ts
- JWT를 검증하는 Guard에서 불필요하게 세션 저장소를 확인하는 로직이 있음을 발견하고 제거하였습니다.
- JWT 검증에서 세션 저장소를 확인하면 JWT를 사용한 의미가 없는건데, 이런 로직을 짜놨더라구요. Wiki 쓰다가 발견하여 PR올립니다.
=> refactor(be): remove unnecessary refresh token check in jwt auth guard

apps/server/src/chats/chats.repository.ts, apps/server/src/common/exceptions/resource.exception.ts, apps/server/src/common/guards/session-token-validation.guard.ts, apps/server/src/questions/questions.repository.ts, apps/server/src/questions/questions.service.ts, apps/server/src/replies/replies.repository.ts, apps/server/src/sessions-auth/sessions-auth.repository.ts, apps/server/src/sessions/sessions.repository.ts, apps/server/src/socket/socket.gateway.ts, apps/server/src/users/users.repository.ts, apps/server/src/users/users.service.ts
- repository에서 try catch문을 전부 제거하고 날 것의 에러를 필터에서 로깅하고 일괄되게 처리하도록 변경했습니다.
- 초기 렌더링 API에서 sessionId의 유효성을 검사하도록 추가했습니다.
- 웹소켓에서 세션과 토큰의 유효성을 검증하도록 추가했습니다.
- close #236
=> refactor(be): refactoring exception handling logic

apps/client/src/components/my/SessionRecord.tsx, apps/client/src/components/qna/ChattingList.tsx, apps/client/src/components/qna/QuestionList.tsx, apps/client/src/pages/MyPage.tsx, apps/client/tests/MyPage.spec.ts, apps/client/tests/QnAPage.spec.ts
- 만료된 세션 숨기기 / 보이기 토글 기능을 추가했습니다.
- 세션 화면에서 현재 세션이 만료되었는지, 진행 중인지 확인할 수 있습니다.
- 테스트
- 세션 목록에서 토글 처리
- 세션 화면에서 만료 여부 확인
<div align='center'>
</div>
- close #247
=> feat(fe): add toggle for hiding expired sessions

apps/client/src/features/auth/auth.api.ts, apps/client/src/routes/session/$sessionId/index.tsx, apps/client/tests/HomePage.spec.ts
- 기존 로그인 / 로그아웃 프로세스 테스트에서 로그아웃 테스트를 제거했습니다.
- 세션 접속시 페이지 타이틀에 세션 타이틀을 추가합니다.
=> test(fe): remove logout flow in login/logout flow test to focus on login process
